import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Demo PWA app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.header_div}>
          <Image className={styles.logo} width={230} height={230} src="/LogoWhite.png"/>
        </div>
        <div className={styles.main_div} >
            <button className={styles.menubutton}><Image width={400} height={101} src="/topbtn.png"/></button>
            <button className={styles.menubutton}><Image width={400} height={101} src="/centerbtn.png"/></button>
            <button className={styles.menubutton}><Image width={400} height={101} src="/botombtn.png"/></button>
        </div>
        <h1 className={styles.Info} >Select your preferred languaje:</h1>
        <div className={styles.languajeSelector}>
          <button className={styles.langButton}><Image width={230} height={230} src="/spain.png"/></button>
          <button className={styles.langButton}><Image width={230} height={230} src="/catalonia.png"/></button>
          <button className={styles.langButton}><Image width={230} height={230} src="/france.png"/></button>
          <button className={styles.langButton}><Image width={230} height={230} src="/italy.png"/></button>
          <button className={styles.langButton}><Image width={230} height={230} src="/britain.png"/></button>
        </div>
      </div>
      
    </div>
  )
}
